apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: write-string
spec:
  params:
    - name: input-string
      type: string
  steps:
    - name: echo
      image: registry.access.redhat.com/ubi9/ubi-minimal@sha256:3685c58885771d2ea14608caeab6a4c3949b973588c29ce91f462b486ee1be25
      env:
        - name: TEXT
          value: $(params.input-string)
      script: |
        #!/bin/bash
        echo $TEXT
      outputs:
        result:
          type: string