apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
  annotations:
    tekton.dev/pipelines.minVersion: "1.0"
spec:
  steps:
    - name: echo
      image: quay.io/libpod/alpine@sha256:fa93b01658e3a5a1686dc3ae55f170d8de487006fb53a28efcd12ab0710a2e5f
      script: |
        #!/bin/sh
        echo "Hello World"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/version: "1.0"
spec:
  tasks:
    - name: hello
      taskRef:
        name: hello
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-world
  generateName: hello-world-
spec:
  pipelineRef:
    name: hello-world
---
apiVersion: triggers.tekton.manon/v1
kind: CronPipelineJob
metadata:
  name: my-cpj
spec:
  cronSpec: "*/5 * * * *"
  pipelineRunRef: hello-world
