apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone
spec:
  tasks:
  - name: clone
    params:
      - name: url
        value: https://github.com/alice17/test-product-alvalent
    workspaces:
      - name: output
        workspace: output
    taskRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/tektoncd/catalog.git
        - name: revision
          value: main
        - name: pathInRepo
          value: task/git-clone/0.9/git-clone.yaml